export { default as Hero1 } from './Hero1'
export { default as Hero2 } from './Hero2'
export { default as Hero3 } from './Hero3'
export { default as Hero4 } from './Hero4'
export { default as Hero5 } from './Hero5'
export { default as Hero6 } from './Hero6'
